@startuml "Diagramme d'analyse d'une application d'interimère"
'https://plantuml.com/class-diagram

!include https://raw.githubusercontent.com/plantuml/plantuml/master/themes/puml-theme-mars.puml

Class Offre{}

Class Inscrit{}

Class Application{}

Class Candidat{}

Class Employeur{}

Class Candidature{}

Class Compte{}

Class Invité{}

Class Utilisateur{}

Application -- Inscrit:possède >
Application -- Invité:possède >

Utilisateur <|-- Invité
Utilisateur <|-- Inscrit

Inscrit <|-- Candidat
Inscrit <|-- Employeur
Inscrit <|-- Administrateur
Inscrit -- Compte: cree / se connecter / gerer >

Invité -- Offre: consulter >

Candidat -- Offre: consulte / mettre en favori >
Candidat -- Offre: postule / suivre >
(Candidat, Offre) .. Candidature
Candidat -- Employeur: discuter >

Employeur -- Offre: cree / gerer >
Employeur -- Candidature: consulter >
Employeur -- Candidat: discuter >

@enduml
